"""Type stubs for the compiled Rust extension module (fastnltk._rust).

These stubs are verified against the actual Rust exports via mypy.stubtest.
"""

# ── Tokenization ─────────────────────────────────────────

def sent_tokenize(text: str, language: str = "english") -> list[str]: ...
def word_tokenize(
    text: str, language: str = "english", preserve_line: bool = False
) -> list[str]: ...

class RegexpTokenizer:
    def __init__(self, pattern: str = r"\w+", gaps: bool = False, flags: int = 0) -> None: ...
    def tokenize(self, text: str) -> list[str]: ...
    def span_tokenize(self, text: str) -> list[tuple[int, int]]: ...

class WhitespaceTokenizer:
    def __init__(self) -> None: ...
    def tokenize(self, text: str) -> list[str]: ...

class WordPunctTokenizer:
    def __init__(self) -> None: ...
    def tokenize(self, text: str) -> list[str]: ...

class BlanklineTokenizer:
    def __init__(self) -> None: ...
    def tokenize(self, text: str) -> list[str]: ...

class LineTokenizer:
    def __init__(self) -> None: ...
    def tokenize(self, text: str) -> list[str]: ...

class SpaceTokenizer:
    def __init__(self) -> None: ...
    def tokenize(self, text: str) -> list[str]: ...

class TabTokenizer:
    def __init__(self) -> None: ...
    def tokenize(self, text: str) -> list[str]: ...

class TreebankWordTokenizer:
    def __init__(self) -> None: ...
    def tokenize(self, text: str) -> list[str]: ...
    def span_tokenize(self, text: str) -> list[tuple[int, int]]: ...

class TreebankWordDetokenizer:
    def __init__(self) -> None: ...
    def detokenize(self, tokens: list[str]) -> str: ...

class TweetTokenizer:
    def __init__(
        self, preserve_case: bool = True, reduce_len: bool = False, strip_handles: bool = False
    ) -> None: ...
    def tokenize(self, text: str) -> list[str]: ...

class MWETokenizer:
    def __init__(
        self, mwe_pairs: list[tuple[str, ...]] | None = None, separator: str = "_"
    ) -> None: ...
    def tokenize(self, text: list[str]) -> list[str]: ...

class ToktokTokenizer:
    def __init__(self) -> None: ...
    def tokenize(self, text: str) -> list[str]: ...

class NISTTokenizer:
    def __init__(self) -> None: ...
    def tokenize(self, text: str) -> list[str]: ...

class SExprTokenizer:
    def __init__(self, strict: bool = True) -> None: ...
    def tokenize(self, text: str) -> list[str]: ...

class CharTokenizer:
    def __init__(self) -> None: ...
    def tokenize(self, text: str) -> list[str]: ...

# ── Stemming ─────────────────────────────────────────────

class SnowballStemmer:
    def __init__(self, language: str = "english") -> None: ...
    def stem(self, word: str) -> str: ...
    def stem_many(self, words: list[str]) -> list[str]: ...

class PorterStemmer:
    def __init__(self) -> None: ...
    def stem(self, word: str) -> str: ...

class LancasterStemmer:
    def __init__(self) -> None: ...
    def stem(self, word: str) -> str: ...

class RegexpStemmer:
    def __init__(self, min_length: int = 0) -> None: ...
    def stem(self, word: str) -> str: ...

class ISRIStemmer:
    def __init__(self) -> None: ...
    def stem(self, word: str) -> str: ...

class Cistem:
    def __init__(self) -> None: ...
    def stem(self, word: str) -> str: ...

class RSLPStemmer:
    def __init__(self) -> None: ...
    def stem(self, word: str) -> str: ...

# ── Tagging ──────────────────────────────────────────────

class PerceptronTagger:
    def __init__(self) -> None: ...
    def tag(self, tokens: list[str]) -> list[tuple[str, str]]: ...
    def tag_sents(self, sentences: list[list[str]]) -> list[list[tuple[str, str]]]: ...

class PosTagger:
    def tag(self, tokens: list[str]) -> list[tuple[str, str]]: ...
    def tag_sents(self, sentences: list[list[str]]) -> list[list[tuple[str, str]]]: ...

# ── Classification ───────────────────────────────────────

class NaiveBayesClassifier:
    def train(self, labeled_featuresets: list[tuple[dict, str]]) -> None: ...
    def classify(self, features: dict) -> str: ...
    def labels(self) -> list[str]: ...

# ── Probability ──────────────────────────────────────────

class FreqDist:
    def __init__(self, samples: list | None = None) -> None: ...
    def __getitem__(self, sample: str) -> int: ...
    def __len__(self) -> int: ...
    def N(self) -> int: ...
    def B(self) -> int: ...
    def freq(self, sample: str) -> float: ...
    def max(self) -> str: ...
    def hapaxes(self) -> list[str]: ...
    def samples(self) -> list[str]: ...
    def update(self, samples: list[str]) -> None: ...
    def most_common(self, n: int | None = None) -> list[tuple[str, int]]: ...
